version: '3.7'
services:
    app:
        image: 'imagem_app'
        container_name: container_app
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                user: userdev
                uid: 1000
        ports:
            - 8080:80
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'hurri_db'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: '12345678'
            MYSQL_ROOT_PASSWORD: '12345'
        volumes:
            - ./.docker/dbdata/mysql:/var/lib/mysql
    db2:
        image: postgres:12.0-alpine
        restart: always
        environment:
            POSTGRES_DB: hurri_db
            POSTGRES_USER: 'dbuser'
            POSTGRES_PASSWORD: '12345678'
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/dbdata/pgsql:/var/lib/postgresql/data
